### ISSUE TITLE
Publish releases for 1.1.2 and 1.1.3

### ISSUE THREAD

**Issue by johnbillion** [humanmade/coding-standards#254]
On the [repo homepage](https://github.com/humanmade/coding-standards) it looks like version 1.1.1 is the latest, despite there being two newer tags for 1.1.2 and 1.1.3.

Can a release be published for each of these please?

**Comment by johnbillion** [comment]
Addendum:

* 1.1.2 is missing from eslint-config: https://www.npmjs.com/package/@humanmade/eslint-config?activeTab=versions
* 1.1.2 and 1.1.3 are missing from stylelint-config: https://www.npmjs.com/package/@humanmade/stylelint-config?activeTab=versions

**Comment by tfrommen** [comment]
Would be great if someone who knows how we handle the individual nested packages with lerna etc. could do that. To me, this is not obvious, and given that we have pushed stuff since the individual tags, I think this will now require additional branches to "fix" that. Un-assigning myself, but pinging @kadamwhite and @ntwb.

**Comment by ntwb** [comment]
I've just published ESLint & Stylelint releases to npm as `next` releases so that they can be tested:

### npm

- https://www.npmjs.com/package/@humanmade/eslint-config
  - To install and test: `npm install --save-dev @humanmade/eslint-config@next`
- https://www.npmjs.com/package/@humanmade/stylelint-config
  - To install and test: `npm install --save-dev @humanmade/stylelint-config@next`

Because Lerna also pushes a Git tag, and tag `v1.2.0` already existed I've pushed this change as `v1.2.1`
- https://github.com/humanmade/coding-standards/releases/tag/v1.2.1

With the npm version bump, the final release of these should be released as v2.0.0 I guess, so once we've tested these `next` package releases we can then publish HMCS to `latest` and tag as `v2.0.0`

### hm-linter

```yml
# GLOBAL SETTINGS

# By default, the version is set to "latest". This can be set to any version
# >=0.4.2, but you MUST include the full version number.
version: 1.2.1

# PER-STANDARD SETTINGS
phpcs:
    # Set to false to disable phpcs
    enabled: true

    # Set to "inherit" to use the global version, "latest" for the latest
    # version, or a specific full version number.
    version: next

eslint:
    enabled: true
    version: inherit

stylelint:
    enabled: true
    version: inherit
```

Or alternatively to only test the `next` version of ESLint only by changing `version: inherit` to `version: next`:

```yml
# GLOBAL SETTINGS

# By default, the version is set to "latest". This can be set to any version 
# >=0.4.2, but you MUST include the full version number.
version: 1.1.2

# PER-STANDARD SETTINGS
phpcs:
    # Set to false to disable phpcs
    enabled: true

    # Set to "inherit" to use the global version, "latest" for the latest
    # version, or a specific full version number.
    version: inherit

eslint:
    enabled: true
    version: next

stylelint:
    enabled: false
    version: inherit
```

Note: It's been quite some time since we published new releases of ESLint & Stylelint configs, I've not tested the above yet, only published, so please if you try any of the above and encounter issues please let me know and create new issues on https://github.com/humanmade/coding-standards as appropriate

Thanks 🙂
